
# DO NOT EDIT THIS FILE IF NOT NECCESSARY 
# FOR MORE INFO PLEASE CONTACT ON: lubiku@proton.me

import modules.target as target             # defined as callback_target
import modules.virustotal as virustotal     # defined as callback_virustotal
import modules.dns as dns                   # defined as callback_dns
import modules.output as output             # defined as callback_output
import modules.whois as whois               # defined as callback_whois
import modules.shodan as shodan             # defined as callback_shodan
import modules.ports as ports               # defined as callback_ports
import modules.screenshots as screenshots   # defined as callback_screenshots
import modules.services as services         # defined as callback_services
import modules.menu as menu                 # defined as callback_menu


def get_user_menu_input():
    # GLOBALS 
    TARGET_INFO = {} 
    
    while True:
        user_menu_input = input("$ ")
        user_menu_input = user_menu_input.replace(" ", "").lower()

        if user_menu_input == "-ti":
            callback_target = target.Target()
            callback_target.define_target_info()
            TARGET_INFO = callback_target.return_target_info()
        elif user_menu_input == "-vt":
            if TARGET_INFO != {}: 
                callback_virustotal = virustotal.Virustotal(target_info=TARGET_INFO)
                callback_virustotal.force_virustotal_subdomain_scan()
                callback_virustotal.test()
            else: print("Dependencies for target info misssing, set target info first by using command -ti")
        elif user_menu_input == "-exit":
            return
    
def main():
    callback_menu = menu.Menu()
    callback_menu.project_menu()
    get_user_menu_input()
